import { Context } from "hono";
import { http_status } from "../../../shared/constants/http";
import { AuthService } from "./auth.service";
import { userRegister } from "./types/user.type";
import { HTTPException } from 'hono/http-exception'

export class AuthController {
    constructor(private authService: AuthService) { }

    async userRegister(body: userRegister) {
        try {
            const user = await this.authService.userRegister(body);

            if (!user) {
                return {
                    statusCode: http_status.BadRequest,
                    success: false,
                    message: "User registration failed",
                };
            }

            return {
                statusCode: http_status.Created,
                success: true,
                message: "User registered successfully",
                data: user,
            };
        } catch (error: any) {
            // check for duplicate email error
            if (error.message.includes("duplicate key") || error.message.includes("already exists")) {
                return {
                    statusCode: http_status.Conflict, // 409
                    success: false,
                    message: "Email already exists",
                };
            }

            console.error(error);
            return {
                statusCode: http_status.InternalServerError, // 500
                success: false,
                message: error.message || "Internal Server Error",
            };
        }
    }
    async userLogin(c: Context<any, any, {}>, body: { emailOrPhone: string, password: string }) {
        try {
            const response = await this.authService.login(                // ✅ Context
                body.emailOrPhone,  // ✅ email or phone
                body.password       // ✅ password
            );
            if (!response) {
                return { statusCode: false, message: "Data Not Found" }
            }
            return response

        } catch (error: any) {
            console.error(error);
            return {
                statusCode: http_status.InternalServerError,
                success: false,
                message: error.message || "Internal Server Error",
            };
        }
    }
    async googleLogin(c: Context<any, any, {}>, body: { idToken: string }): Promise<any> {
        try {
            const idToken = body.idToken;
            if (!idToken) {
                return c.json({
                    statusCode: 400,
                    success: false,
                    message: "idToken is required",
                }, 400);
            }

            const result = await this.authService.googleLogin(idToken);
            // console.log(result);
            return result;

        } catch (err: any) {
            if (err instanceof HTTPException) {
                // Return the error response generated by HTTPException
                return err.getResponse()
            }
            // For any other unexpected errors, log and return a generic 500 response
            console.error(err)
            return c.text('Internal Server Error', 500)
        }
    }
    async updateUser2FactorVerified(c: Context<any, any, {}>, body: { is_verified: boolean }): Promise<any> {
        const user = c.get("user"); // 👈 get from middleware
        const userId = user.uuid;
        console.log(userId,body.is_verified);
        const response = await this.authService.updateVerified(userId, body.is_verified)
        return c.json({
            status: true,
            message:"User Verified",
            response,
        });
    }
}